- name: variables
  hosts: local
  connection: local
  vars: # PLAY level variables, global variables
    COURSE: "DevOps with AWS"
    DURATION: 120HRS
    TRAINER: Sivakumar
  tasks:
    - name: print the variable with task-level variable (overrides)
      vars: # Task level variables, only accessible within this task
        COURSE: Ansible
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"

    - name: print the variable with play-level variable
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"
