- name: variables from files
  hosts: local
  connection: local
  vars:
    GREET: "PLAY"
  vars_files:
  - course.yaml
  vars_prompt:
  - name: GREET
    prompt: Enter the Value
    private: false
  tasks:
  - name: print the variable
    vars:
      GREET: "TASK"
    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}"