- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefine variable
    ansible.builtin.debug:
      # msg: "Hello {{ person}} "
      msg: "Hello {{ person | default("charan") }} "

  - name: Converting string to list
    vars:
      fruits: "apple, banana, orange"    #string
    ansible.builtin.debug:
      msg: "Fruits are: {{ fruits | split(',') }}"
    
  
  - name: Converting map to list
    vars:
      course:
        name: Ansible
        duration: 10hrs
        trainer: siva kumar
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items}}"



  - name: convert list to map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10hrs'}
      - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: "Course info: {{ course | items2dict }}"



  - name: Convert upper to lower
    vars:
      name: "Charan Kandukuri"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"
    

  - name: Convert lower to upper
    vars:
      name: "Charan Kandukuri"
    ansible.builtin.debug:
      msg: " Hello {{ name | lower }}"
  

  - name: Print Minimum and Maximum numbers
    vars:
      numbers: [1,30,54,56,598,62,26]
    ansible.builtin.debug:
      msg: "Min is: {{ numbers | min }}, Max is: {{ numbers | Max }}"

  
  - name: Check ip address is valid or not
    vars:
    ip: "266.255.245.246"           # Give a working ip 
  ansible.builtin.debug:
    msg: "{{ ip | ansible.utils.ipaddr }}"
